version: "3.7"

services:
  java-socket-server:
    container_name: "socket-server-java"
    build:
      context: "."
      dockerfile: "Dockerfile"
    environment:
      TIMEZONE: "America/Sao_Paulo"
      TZ: "America/Sao_Paulo"
      SOCKET_SERVER_PORT: "9090"
      COMMIT_FILE_PATH: "/etc/commit-hash.txt"
      VERSION: "1.0.0"
    volumes:
      - "./commit-hash.txt:/etc/commit-hash.txt"
    ports:
      - 9090:9090

  python-socket-client:
    container_name: "socket-client-python"
    build:
      context: "./python-socket-client/"
      dockerfile: "Dockerfile"
    environment:
      TIMEZONE: "America/Sao_Paulo"
      TZ: "America/Sao_Paulo"
      SOCKET_SERVER_ADDRESS: "java-socket-server"
      SOCKET_SERVER_PORT: "9090"
